#!/usr/bin/env python3
"""Plot Q4 MPI matrix-vector multiplication results.

Reads the CSV files generated by the experiment runner:
  - q4_part1.csv
  - q4_part2.csv
  - q4_part3.csv
  - q4_part4.csv

Creates 8 comparison figures (speedup + efficiency for each part),
with Row-wise 1D and 2D partitioning drawn on the same axes.

Usage:
  python3 plot_q4_comparison.py --input-dir . --output-dir plots_q4
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import pandas as pd


PARTS = {
    1: {
        "csv": "q4_part1.csv",
        "x": "p",
        "title": "Part 1: fixed matrix size (2048×2048), vary p",
        "xlabel": "Number of processors (p)",
    },
    2: {
        "csv": "q4_part2.csv",
        "x": "n",
        "title": "Part 2: fixed p=8, vary matrix size",
        "xlabel": "Matrix dimension (n)",
    },
    3: {
        "csv": "q4_part3.csv",
        "x": "p",
        "title": "Part 3: weak scaling, n = 512 · p",
        "xlabel": "Number of processors (p)",
    },
    4: {
        "csv": "q4_part4.csv",
        "x": "W",
        "title": "Part 4: isoefficiency scaling",
        "xlabel": "W",
    },
}


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing CSV file: {path}")

    df = pd.read_csv(path)

    # Drop rows that contain ERR in key numeric columns.
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="ignore")

    return df


def numeric_only(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        out = out[pd.to_numeric(out[c], errors="coerce").notna()]
    return out.copy()


def prepare_part1_3(df: pd.DataFrame, xcol: str) -> pd.DataFrame:
    needed = [xcol, "speedup1d", "efficiency1d", "speedup2d", "efficiency2d"]
    df = numeric_only(df, needed)
    df[xcol] = pd.to_numeric(df[xcol])
    return df.sort_values(xcol)


def prepare_part2(df: pd.DataFrame) -> pd.DataFrame:
    # Part 2 CSV header is n,p,... but x-axis is n.
    return prepare_part1_3(df, "n")


def prepare_part4(df: pd.DataFrame) -> pd.DataFrame:
    needed = ["W", "k", "speedup1d", "efficiency1d", "speedup2d", "efficiency2d"]
    df = numeric_only(df, needed)
    df["W"] = pd.to_numeric(df["W"])
    return df.sort_values("W")


def plot_metric(df: pd.DataFrame, xcol: str, y1: str, y2: str, title: str, xlabel: str, ylabel: str, outpath: Path, add_ideal: bool = False) -> None:
    plt.figure(figsize=(7.2, 4.8), dpi=160)

    plt.plot(df[xcol], df[y1], marker="o", linewidth=2, label="Row-wise 1D")
    plt.plot(df[xcol], df[y2], marker="s", linewidth=2, label="2D partitioning")

    if add_ideal and ylabel.lower().startswith("eff"):
        plt.axhline(1.0, linestyle="--", linewidth=1.5, label="Ideal efficiency = 1")
    elif add_ideal and ylabel.lower().startswith("speed"):
        # Ideal speedup line: speedup = p only makes sense for parts with xcol = p.
        # Only draw when x-axis is processor count.
        if xcol == "p":
            plt.plot(df[xcol], df[xcol], linestyle="--", linewidth=1.5, label="Ideal speedup = p")

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath)
    plt.close()


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot Q4 comparison figures from CSV files.")
    parser.add_argument("--input-dir", type=Path, default=Path("."), help="Directory containing q4_part*.csv")
    parser.add_argument("--output-dir", type=Path, default=Path("plots_q4"), help="Directory to save figures")
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Part 1
        df1 = prepare_part1_3(read_csv(args.input_dir / PARTS[1]["csv"]), "p")
        plot_metric(df1, "p", "speedup1d", "speedup2d", PARTS[1]["title"] + " — Speedup", PARTS[1]["xlabel"], "Speedup", args.output_dir / "part1_speedup.png", add_ideal=True)
        plot_metric(df1, "p", "efficiency1d", "efficiency2d", PARTS[1]["title"] + " — Efficiency", PARTS[1]["xlabel"], "Efficiency", args.output_dir / "part1_efficiency.png", add_ideal=True)

        # Part 2
        df2 = prepare_part2(read_csv(args.input_dir / PARTS[2]["csv"]))
        plot_metric(df2, "n", "speedup1d", "speedup2d", PARTS[2]["title"] + " — Speedup", PARTS[2]["xlabel"], "Speedup", args.output_dir / "part2_speedup.png", add_ideal=False)
        plot_metric(df2, "n", "efficiency1d", "efficiency2d", PARTS[2]["title"] + " — Efficiency", PARTS[2]["xlabel"], "Efficiency", args.output_dir / "part2_efficiency.png", add_ideal=True)

        # Part 3
        df3 = prepare_part1_3(read_csv(args.input_dir / PARTS[3]["csv"]), "p")
        plot_metric(df3, "p", "speedup1d", "speedup2d", PARTS[3]["title"] + " — Speedup", PARTS[3]["xlabel"], "Speedup", args.output_dir / "part3_speedup.png", add_ideal=True)
        plot_metric(df3, "p", "efficiency1d", "efficiency2d", PARTS[3]["title"] + " — Efficiency", PARTS[3]["xlabel"], "Efficiency", args.output_dir / "part3_efficiency.png", add_ideal=True)

        # Part 4
        df4 = prepare_part4(read_csv(args.input_dir / PARTS[4]["csv"]))
        # Using W on x-axis keeps the plot aligned with the assignment statement.
        plot_metric(df4, "W", "speedup1d", "speedup2d", PARTS[4]["title"] + " — Speedup", PARTS[4]["xlabel"], "Speedup", args.output_dir / "part4_speedup.png", add_ideal=False)
        plot_metric(df4, "W", "efficiency1d", "efficiency2d", PARTS[4]["title"] + " — Efficiency", PARTS[4]["xlabel"], "Efficiency", args.output_dir / "part4_efficiency.png", add_ideal=True)

    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    print(f"Saved 8 figures to: {args.output_dir.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
